### PR TITLE
Implement a serde deserializer

### PR DESCRIPTION
**Pull request by erickt**
This draws inspiration from @burntsushi's [csv](https://github.com/burntsushi/rust-csv). This adds a `RangeDeserializerBuilder`, `RangeDeserializer`, and `ToCellDeserializer`, which work together to iterate over each row in a `Range`, all while deserializing the row into some deserializable type.

Some questions:

* One thing to note is that it assumes that the first row is the header. One needs to use the Builder to disable this. Is this the right choice?
* Should the builder be exposed on `Range`?
* It feels like I ought to be working with `Cell`s, not `CellType`s, but it doesn't seem like cells are getting much use.
* Should `DataTypeDeserializer` be exposed more directly, where it is constructed with a (0,0) position?

Implements the deserialization part of #96.

Also, this bumps the error-chain dependency to 0.11.

### CODE REVIEW

**Comment by tafia** [comment]
This is awesome thanks!! 
I do not have lot of time this week but I plan to review it properly next week.
Thanks!

**Comment by erickt** [comment]
Happy to help! calamine was a great help processing the rust community survey, so it was the least I could do :)

**Comment by tafia** [comment]
Very happy to hear that!

**Comment by tafia** [comment]
This is very, very, very nice thanks again!

I must confess I do not fully understand it all. It looks like there are a lot of intermediary struct/trait I wouldn't have used. 

That said: 
- I am really no serde expert, 
- it is not breaking anything and all doc tests pass
- it adds a very wanted feature to calamine
- you and @BurntSushi are probably far better programmer than me

I'm happy to merge, I'll release a new version asap.
Thanks again, this is no small work.

**Comment by tafia** [comment]
version 0.12.0 published!

**Pull request merged**
