### PR TITLE
bump quick-xml to version 0.22

### LINKED ISSUE #248: Bump quick-xml dependency
calamine is set to use quick-xml 0.19.0, this should probably be at least 0.22.0? It compiles fine with the 0.23.0 alpha in Fedora

### PR DESCRIPTION
**Pull request by striezel**
This should close #248.

### CODE REVIEW

**Comment by striezel** [comment]
@tafia: No activity here for more than two months. Did you just miss this PR or is something wrong with it? Please let me know whether something prevents the merge of this PR so that I can fix it. :)

**Comment by striezel** [comment]
Hey @tafia, I'm pinging you here as a friendly remonder, because it seems like you forgot about that PR. It's been almost four months now, so I would really appreciate any feedback here.

**Comment by striezel** [comment]
Rebased against current master branch to fix merge conflicts.

**Comment by striezel** [comment]
Rebased against current master branch, again.

I am aware that `quick-xml` version 0.25 has been released in the meantime, but `calamine` would need a non-trivial amount of other code adjustments to compile with `quick-xml` version 0.25, so I am leaving this at version 0.22.

**Comment by tafia** [comment]
Thanks!

**Comment by striezel** [comment]
Thanks for merging this pull request (as well as the others), and thanks for the new 0.19.x releases. :)

**Pull request merged**
