### PR TITLE
Fix indexing

### PR DESCRIPTION
**Pull request by tafia**
Fix various bugs listed in #114 

- [x] Empty worksheet considered 1x1
- [x] Column 0 not accessible in 30x6 worksheet

### CODE REVIEW

**Comment by tafia** [comment]
@sanmai-NL do you have a test file for the 30x6 failing test.
Can you also check if your issue is fixed for the empty sheet?

**Comment by sanmai-NL** [comment]
@tafia: Sent you an e-mail with more info. :slightly_smiling_face:

**Comment by tafia** [comment]
Thanks @sanmai-NL 

Sorry for the wait.

I have tested your files and I managed to read them all (at least with this PR).

I think there is an error with your code in #114, instead of using `Range::get_value`, you should be using the `Index` trait directly, i.e. `range[(0, 0)]`.

Indeed the `get_value` expects an **absolute** value whereas in your example the range value were starting at row 1 (not 0) only.

I have modified the `get_value` fn so it'll return an `Option` instead. I have also improved the comments so hopefully it'll be clearer. I couldn't find a better name though (which is not too long).

**Comment by sanmai-NL** [comment]
Thanks! I had some issues using relative indexes and I also wanted to prevent panics. Thanks for improving the code, I will try it out soon.

**Comment by tafia** [comment]
>  I had some issues using relative indexes

Just to be sure I was clear. If you want to continue using absolute indexes, you must loop from `start` to `end` instead of from `(0, 0)` to `size`.

Let me know!

**Comment by sanmai-NL** [comment]
Ah okay, that clarifies things.

**Pull request merged**
