### PR TITLE
Dependency bump and clippy

### PR DESCRIPTION
**Pull request by jqnatividad**
bump dependencies and apply select clippy lint suggestions

### CODE REVIEW

**Comment by jqnatividad** [comment]
Hi @tafia ,
The PR is failing the Rust 1.60.0 test because the `flate2` crate is deriving defaults on enums.

This feature has been [stable since Rust 1.62](https://github.com/rust-lang/rust/pull/94457).  Do you need calamine to work on 1.60 for a particular reason?

**Comment by tafia** [comment]
I'm afraid there is now a conflict though due to older PR being merged. Could you fix it?

**Comment by jqnatividad** [comment]
Hi @tafia ,
I resolved the conflicts and bumped MSRV to 1.62.1 and edition to 2021.

I also went ahead and derived Default for DataType now that we're using 1.62.1.

**Comment by tafia** [comment]
Awesome thanks!

**Pull request merged**
