### PR TITLE
Rename `DataType` methods `as_f64` `as_i64` into `as_float` `as_int`

### PR DESCRIPTION
**Pull request by lucatrv**

### CODE REVIEW

**Comment by lucatrv** [comment]
@tafia can this be merged or is anything else needed?

**Comment by tafia** [comment]
There are conflicts, sorry it is because of another PR I just merged.

**Comment by lucatrv** [comment]
@tafia, sorry I just had a second thought about this, maybe the reason for the current nonuniform naming is because:

- `is_float` means: check if the `Data` variant is `Float`.
- `get_float` means: if the `Data` variant is `Float`, get its content.
- `as_f64` means: try to convert any `Data` variant into an `f64` type.

In this case, maybe the current naming is correct. Please let me know your thought, then I will either close this PR or resolve its conflicts for merging.
I am ready to create a new PR to add deserialize helping function which will work similarly to [`csv::invalid_option`](https://docs.rs/csv/latest/csv/tutorial/index.html#handling-invalid-data-with-serde), but I am stuck due to this PR, so I hope you'll let me know soon.
Thanks

**Comment by tafia** [comment]
Sorry for the late answer. Yes this was the idea but I too am unsure about the names.
If you are unsure, then let's not do anything so it won't break too much code.
I let it opened for now for other people to comment either way.

**Comment by lucatrv** [comment]
> Sorry for the late answer. Yes this was the idea but I too am unsure about the names. If you are unsure, then let's not do anything so it won't break too much code. I let it opened for now for other people to comment either way.

Yes I agree, so I will create a PR to close issue #339 using `as_f64` and `as_i64`.

**Comment by lucatrv** [comment]
I am closing this because I think that the current naming is fine

**Pull request closed without merging**
